# Generated by Django 3.0.4 on 2020-03-25 04:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter your valid contact number.', regex='(^[+0-9]{1,3})*([0-9]{10,11}$)')], verbose_name='mobile')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter your valid contact number.', regex='(^[+0-9]{1,3})*([0-9]{10,11}$)')], verbose_name='telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('country_code2', models.CharField(blank=True, max_length=3, null=True, verbose_name='country code')),
                ('dialing_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='dialing code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line1')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line2')),
                ('zip', models.CharField(blank=True, max_length=20, null=True, verbose_name='zip')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contact.Country', verbose_name='country')),
            ],
        ),
    ]
