# Generated by Django 3.0.4 on 2020-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
    ]
