# Generated by Django 3.0.4 on 2020-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20200325_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='created_at',
            field=models.DateField(verbose_name='created at'),
        ),
    ]
